# src/AppBundle/Resources/config/routing.yml

connect:
    path:     /connect
    defaults: { _controller: AppBundle:Accueil:index }

connexion:
    path:     /fut/connect
    defaults: { _controller: AppBundle:Fut:connect }
