# src/AppBundle/Resources/config/routing.yml

home:
    path:     /home
    defaults: { _controller: AppBundle:Accueil:index }

fut:
    path:     /fut
    defaults: { _controller: AppBundle:Fut:index }

connexion:
    path:     /fut/connect
    defaults: { _controller: AppBundle:Fut:connect }